name: Replace tokken for GitHub secrets.
description: This composite action replaces tokens for secrets defined on repository or organization level.

inputs:
  root-directory:
    description: root directory to apply filering on.
    required: true
  file-mask:
    description: filters files for secrets search.
    required: true
  replacement-regex:
    description: 'provides regex to seek for replacements (default: #\{(.*)\}#).'
    required: false
    default: '#\{(.*)\}#'

runs:
  using: composite
  steps:
    - name: replace with pwoershell.
      shell: pwsh
      run: |
        $Files = Get-ChildItem -Path ${{ inputs.root-directory }} -Filter ${{ inputs.file-mask }} -Recurse
        foreach ($File in $Files) {
          $Content = Get-Content $File.FullName
          $Matches = [regex]::matches($Content, "${{ inputs.replacement-regex }}")
          foreach ($Match in $Matches) {
            $SecretName = $Match.Value

            
          }
        }