name: Sync KV secrets to repository secrets
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: false
        type: string
        default: 'dev'

jobs:
  sync:
    uses: aaart/reusable/.github/workflows/kv-secret-sync.yml@main
    with:
      env: ${{ inputs.env }}
      terraform_version: '1.5.3'
      runs-on: ubuntu-latest
    secrets:
      gh-pat: ${{ secrets.GH_PAT }}
      tenant-id: ${{ secrets.TENANT_ID }}
      subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
      client-id: ${{ secrets.CLIENT_ID }}
      client-secret: ${{ secrets.CLIENT_SECRET }}
      kv-repository-secrets: ${{ vars.UMGMT_KV_REPOSITORY_SECRETS }}
      kv-repository-secrets-rg-name: ${{ vars.UMGMT_KV_REPOSITORY_SECRETS_RG_NAME }}
      terraform-resource-group: ${{ vars.TERRAFORM_RESOURCE_GROUP }}
      terraform-storage-account-name: ${{ vars.TERRAFORM_STORAGE_ACCOUNT_NAME }}
      terraform-container-name: ${{ vars.TERRAFORM_CONTAINER_NAME }}
      terraform-backend-key: ${{ vars.TERRAFORM_BACKEND_KEY_SYNC_SECRETS }}

      