name: Sync KV secrets to repository secrets
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: false
        type: string
        default: 'dev'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sync
        uses: aaart/reusable/.github/workflows/kv-secret-sync.yml@main
        with:
          env: ${{ github.event.inputs.env }}