name: Sync KV secrets to repository secrets
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: false
        type: string
        default: 'dev'

jobs:
  get-vars:
    name: Get Environment variables and secrets
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    outputs:
      tenant-id: ${{ steps.get-secrets.outputs.tenant-id }}
      subscription-id: ${{ steps.get-secrets.outputs.subscription-id }}
      client-id: ${{ steps.get-secrets.outputs.client-id }}
      client-secret: ${{ steps.get-secrets.outputs.client-secret }}
      kv-name: ${{ steps.get-vars.outputs.kv-name }}
      kv-rg-name: ${{ steps.get-vars.outputs.kv-rg-name }}
      terraform-resource-group: ${{ steps.get-vars.outputs.terraform-resource-group }}
      terraform-storage-account-name: ${{ steps.get-vars.outputs.terraform-storage-account-name }}
      terraform-container-name: ${{ steps.get-vars.outputs.terraform-container-name }}
      terraform-backend-key: ${{ steps.get-vars.outputs.terraform-backend-key }}
    steps:
      - id: get-secrets
        shell: pwsh
        run: |
          'tenant-id="${{ secrets.UMGMT_TENANT_ID }}"' | Out-File $Env:GITHUB_OUTPUT -Append
          'subscription-id="${{ secrets.UMGMT_SUBSCRIPTION_ID }}"' | out-file $env:GITHUB_OUTPUT -append
          'client-id="${{ secrets.UMGMT_CLIENT_ID }}"' | out-file $env:GITHUB_OUTPUT -append
          'client-secret="${{ secrets.UMGMT_CLIENT_SECRET }}"' | out-file $env:GITHUB_OUTPUT -append
      - id: get-vars
        shell: pwsh
        run: |
          'kv-name="${{ vars.UMGMT_KV_REPOSITORY_SECRETS }}"' | out-file $env:GITHUB_OUTPUT -append
          'kv-rg-name="${{ vars.UMGMT_KV_REPOSITORY_SECRETS_RG_NAME }}"' | out-file $env:GITHUB_OUTPUT -append
          'terraform-resource-group="${{ vars.TERRAFORM_RESOURCE_GROUP }}"' | out-file $env:GITHUB_OUTPUT -append
          'terraform-storage-account-name="${{ vars.TERRAFORM_STORAGE_ACCOUNT_NAME }}"' | out-file $env:GITHUB_OUTPUT -append
          'terraform-container-name="${{ vars.TERRAFORM_CONTAINER_NAME }}"' | out-file $env:GITHUB_OUTPUT -append
          'terraform-backend-key="${{ vars.TERRAFORM_BACKEND_KEY_SYNC_SECRETS }}"' | out-file $env:GITHUB_OUTPUT -append

  sync:
    needs: get-vars
    uses: aaart/reusable/.github/workflows/kv-secret-sync.yml@main
    with:
      env: ${{ inputs.env }}
      terraform_version: '1.5.3'
      runs-on: ubuntu-latest
      kv-repository-secrets: ${{ needs.get-vars.outputs.kv-name }}
      kv-repository-secrets-rg-name: ${{ needs.get-vars.outputs.kv-rg-name }}
      terraform-resource-group: ${{ needs.get-vars.outputs.terraform-resource-group }}
      terraform-storage-account-name: ${{ needs.get-vars.outputs.terraform-storage-account-name }}
      terraform-container-name: ${{ needs.get-vars.outputs.terraform-container-name }}
      terraform-backend-key: ${{ needs.get-vars.outputs.terraform-backend-key }}
    secrets:
      gh-pat: ${{ secrets.GH_PAT }}
      tenant-id: ${{ needs.get-vars.outputs.tenant-id }}
      subscription-id: ${{ needs.get-vars.outputs.subscription-id }}
      client-id: ${{ needs.get-vars.outputs.client-id }}
      client-secret: ${{ needs.get-vars.outputs.client-secret }}

      