name: Sync KV secrets to repository secrets
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: false
        type: string
        default: 'dev'

jobs:
  sync:
    runs-on: ubuntu-22.04
    environment: ${{ inputs.env }}
    steps:
    - run: echo "Deploying to ${{ inputs.env }}"

    - name: checkout
      uses: actions/checkout@v2

    - name: runner details
      run: |
        echo ${{ runner.os }}
        echo ${{ runner.arch }}
        echo ${{ runner.name }}

    # - name: Install AZ CLI for non github hosted runner
    #   #if: runner.os != 'Linux'
    #   uses: pietrobolcato/install-azure-cli-action@main


    - name: install terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.2

    - name: terraform init
      shell: bash
      run: |
        terraform -chdir=$GITHUB_WORKSPACE/terraform/kv-to-repo-secrets/res \
        init \
        -reconfigure \
        -backend-config=resource_group_name=$TERRAFORM_RESOURCE_GROUP \
        -backend-config=storage_account_name=$TERRAFORM_STORAGE_ACCOUNT_NAME \
        -backend-config=container_name=$TERRAFORM_CONTAINER_NAME \
        -backend-config=key=iac-training-secrets.tfstate \
        -backend-config=tenant_id=$TENANT_ID \
        -backend-config=subscription_id=$TERRAFORM_SUBSCRIPTION_ID \
        -backend-config=client_id=$TERRAFORM_CLIENT_ID \
        -backend-config=client_secret=$TERRAFORM_CLIENT_SECRET

    - name: az cli login
      uses: azure/login@v1
      with:
        creds: '{"tenantId": "${{ secrets.UMGMT_TENANT_ID }}", "subscriptionId": "${{ secrets.UMGMT_SUBSCRIPTION_ID }}", "clientId": "${{ secrets.UMGMT_CLIENT_ID }}", "clientSecret": "${{ secrets.UMGMT_CLIENT_SECRET }}"}'
        #creds: ${{ secrets.UMGMT_AZURE_CREDS }}
        enable-AzPSSession: true

    - name: az cli Logout
      run: |
        az logout
        az cache purge
        az account clear
