name: Sync KV secrets to repository secrets
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: false
        type: string
        default: 'dev'

jobs:
  sync:
    uses: aaart/reusable/.github/workflows/kv-secret-sync.yml@main
    with:
      env: ${{ github.event.inputs.env }}