name: Sync KV secrets to repository secrets
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: false
        type: string
        default: 'dev'

jobs:
  get-vars:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    outputs:
      kv-name: ${{ steps.get-kv-name.outputs.kv-name }}
      kv-rg-name: ${{ steps.get-kv-rg-name.outputs.kv-rg-name }}
      terraform-resource-group: ${{ steps.get-tf-rg.outputs.terraform-resource-group }}
      terraform-storage-account-name: ${{ steps.get-tf-storage-account-name.outputs.terraform-storage-account-name }}
      terraform-container-name: ${{ steps.get-tf-container-name.outputs.terraform-container-name }}
      terraform-backend-key: ${{ steps.get-tf-backend-key.outputs.terraform-backend-key }}
    steps:
      - id: get-kv-name
        run: echo kv-name="${{ vars.UMGMT_KV_REPOSITORY_SECRETS }}" >> $GITHUB_OUTPUT
      - id: get-kv-rg-name
        run: echo kv-rg-name="${{ vars.UMGMT_KV_REPOSITORY_SECRETS_RG_NAME }}" >> $GITHUB_OUTPUT
      - id: get-tf-rg
        run: echo terraform-resource-group="${{ vars.TERRAFORM_RESOURCE_GROUP }}" >> $GITHUB_OUTPUT
      - id: get-tf-storage-account-name
        run: echo terraform-storage-account-name="${{ vars.TERRAFORM_STORAGE_ACCOUNT_NAME }}" >> $GITHUB_OUTPUT
      - id: get-tf-container-name
        run: echo terraform-container-name="${{ vars.TERRAFORM_CONTAINER_NAME }}" >> $GITHUB_OUTPUT
      - id: get-tf-backend-key
        run: echo terraform-backend-key="${{ vars.TERRAFORM_BACKEND_KEY_SYNC_SECRETS }}" >> $GITHUB_OUTPUT

  sync:
    needs: get-vars
    uses: aaart/reusable/.github/workflows/kv-secret-sync.yml@main
    with:
      env: ${{ inputs.env }}
      terraform_version: '1.5.3'
      runs-on: ubuntu-latest
    secrets:
      gh-pat: ${{ secrets.GH_PAT }}
      tenant-id: ${{ secrets.UMGMT_TENANT_ID }}
      subscription-id: ${{ secrets.UMGMT_SUBSCRIPTION_ID }}
      client-id: ${{ secrets.UMGMT_CLIENT_ID }}
      client-secret: ${{ secrets.UMGMT_CLIENT_SECRET }}
      kv-repository-secrets: ${{ needs.get-vars.outputs.kv-name }}
      kv-repository-secrets-rg-name: ${{ needs.get-vars.outputs.kv-rg-name }}
      terraform-resource-group: ${{ needs.get-vars.outputs.terraform-resource-group }}
      terraform-storage-account-name: ${{ needs.get-vars.outputs.terraform-storage-account-name }}
      terraform-container-name: ${{ needs.get-vars.outputs.terraform-container-name }}
      terraform-backend-key: ${{ needs.get-vars.outputs.terraform-backend-key }}

      