name: Sync KV secrets to repository secrets
on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: false
        type: string
        default: 'dev'

jobs:
  get-vars:
    name: Get Environment variables and secrets
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    outputs:
      tenant-id: ${{ steps.get-secrets.outputs.tenant-id }}
      subscription-id: ${{ steps.get-secrets.outputs.subscription-id }}
      client-id: ${{ steps.get-secrets.outputs.client-id }}
      client-secret: ${{ steps.get-secrets.outputs.client-secret }}
      kv-name: ${{ steps.get-vars.outputs.kv-name }}
      kv-rg-name: ${{ steps.get-vars.outputs.kv-rg-name }}
      terraform-resource-group: ${{ steps.get-vars.outputs.terraform-resource-group }}
      terraform-storage-account-name: ${{ steps.get-vars.outputs.terraform-storage-account-name }}
      terraform-container-name: ${{ steps.get-vars.outputs.terraform-container-name }}
      terraform-backend-key: ${{ steps.get-vars.outputs.terraform-backend-key }}
    steps:
      - id: get-secrets
        shell: bash
        run: |
          # echo tenant-id="${{ secrets.UMGMT_TENANT_ID }}" >> $GITHUB_OUTPUT
          echo TENANT_ID="${{ secrets.UMGMT_TENANT_ID }}" >> $GITHUB_ENV
          # $env:GITHUB_ENV += "tenant-id=${{ secrets.UMGMT_TENANT_ID }}"
          echo subscription-id="${{ secrets.UMGMT_SUBSCRIPTION_ID }}" >> $GITHUB_OUTPUT
          echo SUBSCRIPTION_ID="${{ secrets.UMGMT_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo client-id="${{ secrets.UMGMT_CLIENT_ID }}" >> $GITHUB_OUTPUT
          echo CLIENT_ID="${{ secrets.UMGMT_CLIENT_ID }}" >> $GITHUB_ENV
          echo client-secret="${{ secrets.UMGMT_CLIENT_SECRET }}" >> $GITHUB_OUTPUT
          echo CLIENT_SECRET="${{ secrets.UMGMT_CLIENT_SECRET }}" >> $GITHUB_ENV
      - id: get-vars
        shell: pwsh
        run: |
          $Env:GITHUB_OUTPUT += 'kv-name="${{ vars.UMGMT_KV_REPOSITORY_SECRETS }}"'
          $Env:GITHUB_OUTPUT += 'kv-rg-name="${{ vars.UMGMT_KV_REPOSITORY_SECRETS_RG_NAME }}"'
          $Env:GITHUB_OUTPUT += 'terraform-resource-group="${{ vars.TERRAFORM_RESOURCE_GROUP }}"'
          $Env:GITHUB_OUTPUT += 'terraform-storage-account-name="${{ vars.TERRAFORM_STORAGE_ACCOUNT_NAME }}"'
          $Env:GITHUB_OUTPUT += 'terraform-container-name="${{ vars.TERRAFORM_CONTAINER_NAME }}"'
          $Env:GITHUB_OUTPUT += 'terraform-backend-key="${{ vars.TERRAFORM_BACKEND_KEY_SYNC_SECRETS }}"'

  sync:
    needs: get-vars
    uses: aaart/reusable/.github/workflows/kv-secret-sync.yml@main
    with:
      env: ${{ inputs.env }}
      terraform_version: '1.5.3'
      runs-on: ubuntu-latest
    secrets:
      gh-pat: ${{ secrets.GH_PAT }}
      tenant-id: ${{ needs.get-vars.outputs.tenant-id }}
      subscription-id: ${{ needs.get-vars.outputs.subscription-id }}
      client-id: ${{ needs.get-vars.outputs.client-id }}
      client-secret: ${{ needs.get-vars.outputs.client-secret }}
      kv-repository-secrets: ${{ needs.get-vars.outputs.kv-name }}
      kv-repository-secrets-rg-name: ${{ needs.get-vars.outputs.kv-rg-name }}
      terraform-resource-group: ${{ needs.get-vars.outputs.terraform-resource-group }}
      terraform-storage-account-name: ${{ needs.get-vars.outputs.terraform-storage-account-name }}
      terraform-container-name: ${{ needs.get-vars.outputs.terraform-container-name }}
      terraform-backend-key: ${{ needs.get-vars.outputs.terraform-backend-key }}

      